// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oytupgguadlpgkzigykz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95dHVwZ2d1YWRscGdremlneWt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyNTQwMjYsImV4cCI6MjA4ODgzMDAyNn0.0tShONNVTm0y4vsltOeh-EjG6tUjX53pu6FeQrHJ8d8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});